/**
 * AI工具集 - 本地数据（106个工具）
 * 当API不可用时自动降级使用此数据
 */

const TOOLS_DATA = [
    {
        id: "1",
        name: "ChatGPT",
        icon: "sparkles",
        description: "OpenAI推出的全球领先对话AI，通过大规模语言模型实现自然语言问答、创作、编程等全能任务，是目前应用最广泛的AI助手之一。",
        summary: "全球领先的对话AI助手",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://chat.openai.com",
        category: "chat",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "2",
        name: "Claude",
        icon: "sparkles",
        description: "Anthropic开发的AI助手，以长上下文理解能力和安全对齐著称，支持超长文档分析、代码撰写、创意写作，表现出色且风格严谨。",
        summary: "安全长上下文AI助手",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://claude.ai",
        category: "chat",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "3",
        name: "豆包",
        icon: "sparkles",
        description: "字节跳动推出的国产大模型AI助手，支持对话、写作、翻译、编程等多种任务，内置于抖音等多款字节产品生态中，用户基数庞大。",
        summary: "字节跳动旗下国产AI助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://www.doubao.com",
        category: "chat",
        pricing: "免费",
        featured: true
    },    {
        id: "4",
        name: "Kimi",
        icon: "sparkles",
        description: "月之暗面推出的国产长文本AI助手，支持20万字超长上下文，擅长阅读和总结长文档、学术论文、法律合同，特别适合深度研究和分析任务。",
        summary: "超长上下文国产AI助手",
        tags: ["免费", "国产"],
        url: "https://kimi.moonshot.cn",
        category: "chat",
        pricing: "免费",
        featured: true
    },    {
        id: "5",
        name: "智谱清言",
        icon: "sparkles",
        description: "智谱AI自研大模型推出的对话助手，基于GLM系列国产基座模型，支持多轮对话、知识问答、代码生成，覆盖通用和专业领域。",
        summary: "智谱AI国产大模型助手",
        tags: ["免费", "国产"],
        url: "https://www.zhipuai.cn",
        category: "chat",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "6",
        name: "Midjourney",
        icon: "sparkles",
        description: "全球最热门的AI绘图工具之一，通过文字描述即可生成高质量艺术风格图像，支持风格定制和参数调整，广泛用于设计、创作和灵感探索。",
        summary: "文字生成艺术图像的AI绘图工具",
        tags: ["付费订阅", "国际"],
        url: "https://www.midjourney.com",
        category: "image",
        pricing: "付费订阅",
        featured: true
    },    {
        id: "7",
        name: "Stable Diffusion",
        icon: "sparkles",
        description: "开源免费的AI图像生成模型，支持本地部署和自定义训练，可生成插画、照片、写实风格等多种图像，是AI绘图领域的重要里程碑。",
        summary: "开源免费AI图像生成模型",
        tags: ["免费", "开源", "国际"],
        url: "https://stability.ai",
        category: "image",
        pricing: "免费",
        featured: true
    },    {
        id: "8",
        name: "通义万相",
        icon: "sparkles",
        description: "阿里云推出的AI绘画创作工具，基于通义大模型，支持中文 prompt 生成高质量图像，提供多种艺术风格，覆盖设计、创意和商业场景。",
        summary: "阿里云AI绘画创作工具",
        tags: ["免费", "国产", "大厂"],
        url: "https://tongyi.aliyun.com/wanxiang",
        category: "image",
        pricing: "免费",
        featured: true
    },    {
        id: "9",
        name: "文心一格",
        icon: "sparkles",
        description: "百度文心大模型出品的AI艺术创作平台，支持中文 Prompt 输入，生成国风、插画、写实等多样风格图像，与百度搜索生态深度整合。",
        summary: "百度文心AI艺术创作平台",
        tags: ["免费", "国产", "大厂"],
        url: "https://yige.baidu.com",
        category: "image",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "10",
        name: "秒画",
        icon: "sparkles",
        description: "商汤科技推出的AI图像生成工具，支持超写实风格和多种画风，基于商汤大模型，生成速度快、质量高，适合创意设计和商业应用。",
        summary: "商汤科技AI图像生成工具",
        tags: ["免费", "国产", "大厂"],
        url: "https://miaohua.sensetime.com",
        category: "image",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "11",
        name: "GitHub Copilot",
        icon: "sparkles",
        description: "微软与 GitHub 联合推出的AI代码助手，深度集成于 VS Code 等主流IDE，实时提供代码补全、函数生成、注释转代码，大幅提升开发者编程效率。",
        summary: "微软AI代码补全助手",
        tags: ["付费订阅", "国际", "大厂"],
        url: "https://github.com/features/copilot",
        category: "code",
        pricing: "付费订阅",
        featured: true
    },    {
        id: "12",
        name: "Cursor",
        icon: "sparkles",
        description: "专为AI时代打造的代码编辑器，基于 VS Code 内核，支持多模型切换、代码预测、AI聊天编辑，引领AI原生IDE潮流，深受开发者喜爱。",
        summary: "AI原生代码编辑器",
        tags: ["免费", "国际", "创新"],
        url: "https://cursor.com",
        category: "code",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "13",
        name: "通义灵码",
        icon: "sparkles",
        description: "阿里云推出的智能编码辅助工具，深度集成于 IDE 和 Git 开发流程，支持代码补全、续写、生成单元测试、代码审查等全场景能力。",
        summary: "阿里云智能编程助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://tongyi.aliyun.com/lingma",
        category: "code",
        pricing: "免费",
        featured: true
    },    {
        id: "14",
        name: "秘塔写作猫",
        icon: "sparkles",
        description: "国内领先的AI写作辅助工具，提供错别字纠正、语病检测、表达润色、续写扩写等功能，是新媒体作者、学生和职场人士的写作好帮手。",
        summary: "AI智能写作润色工具",
        tags: ["免费", "国产"],
        url: "https://xiezuocat.com",
        category: "writing",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "15",
        name: "讯飞写作",
        icon: "sparkles",
        description: "科大讯飞推出的AI写作工具，依托讯飞星火大模型，支持文章生成、模板写作、多语言翻译和语音输入转写，适用于办公和内容创作场景。",
        summary: "科大讯飞AI写作助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://turbos.foxicm.com",
        category: "writing",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "16",
        name: "Runway",
        icon: "sparkles",
        description: "前沿的AI视频生成和编辑平台，支持文字转视频、图像生成视频、视频风格迁移和绿幕抠像等功能，是AI视频创作领域的领跑者。",
        summary: "AI视频生成与编辑平台",
        tags: ["付费订阅", "国际"],
        url: "https://runwayml.com",
        category: "video",
        pricing: "付费订阅",
        featured: true
    },    {
        id: "17",
        name: "Gamma",
        icon: "sparkles",
        description: "AI驱动的演示文稿和文档生成工具，只需输入文字描述即可自动生成精美的PPT、网页和文档，大幅节省设计排版时间。",
        summary: "AI演示文稿生成工具",
        tags: ["免费", "国际"],
        url: "https://gamma.app",
        category: "video",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "18",
        name: "Notion AI",
        icon: "sparkles",
        description: "Notion内置的AI写作助手，帮助用户快速生成、总结、翻译、润色笔记内容，与知识库无缝结合，是知识管理和团队协作的效率利器。",
        summary: "Notion内置AI写作助手",
        tags: ["付费订阅", "国际"],
        url: "https://notion.so",
        category: "writing",
        pricing: "付费订阅",
        featured: true
    },    {
        id: "19",
        name: "可灵AI",
        icon: "sparkles",
        description: "快手推出的AI视频生成大模型，支持文字生成视频和图像生成视频，生成的视频运动流畅、画质细腻，对标国际顶级视频生成模型。",
        summary: "快手AI视频生成大模型",
        tags: ["免费", "国产", "大厂"],
        url: "https://klingai.kuaishou.com",
        category: "video",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "20",
        name: "腾讯混元",
        icon: "sparkles",
        description: "腾讯推出的国产大模型，集成于微信、QQ等腾讯生态，支持智能对话、内容创作、代码生成和图片理解，生态优势明显。",
        summary: "腾讯自研国产大模型",
        tags: ["免费", "国产", "大厂"],
        url: "https://hunyuan.tencent.com",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "21",
        name: "Sora",
        icon: "sparkles",
        description: "OpenAI推出的革命性AI视频生成模型，能够根据文本描述生成长达60秒的高清视频，支持复杂场景渲染和多角色互动，被视为AI视频的里程碑。",
        summary: "OpenAI文生视频大模型",
        tags: ["付费订阅", "国际"],
        url: "https://openai.com/sora",
        category: "video",
        pricing: "付费订阅",
        featured: true
    },    {
        id: "22",
        name: "Suno",
        icon: "sparkles",
        description: "全球领先的AI音乐生成平台，只需输入文字描述即可创作包含歌词、旋律和人声的完整歌曲，支持多种音乐风格，普通用户也能生成专业级音乐作品。",
        summary: "AI音乐创作平台",
        tags: ["免费", "国际"],
        url: "https://suno.ai",
        category: "audio",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "23",
        name: "Perplexity",
        icon: "sparkles",
        description: "基于AI的对话式搜索引擎，实时联网获取最新信息，提供带来源引用的精准回答，是传统搜索体验的重大革新，被称作AI时代的搜索引擎。",
        summary: "AI对话式搜索引擎",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://www.perplexity.ai",
        category: "search",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "24",
        name: "文心一言",
        icon: "sparkles",
        description: "百度基于文心大模型推出的生成式AI产品，支持中文对话、文学创作、商业文案、代码编写、数理逻辑等，具有强大的中文理解和生成能力。",
        summary: "百度文心大模型对话助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://yiyan.baidu.com",
        category: "chat",
        pricing: "免费",
        featured: true
    },    {
        id: "25",
        name: "通义千问",
        icon: "sparkles",
        description: "阿里云自研的大语言模型，支持中英文对话、代码编写、知识问答等功能，已开源多款模型，生态丰富，企业和个人用户均可便捷使用。",
        summary: "阿里云大语言模型",
        tags: ["免费", "开源", "国产"],
        url: "https://tongyi.aliyun.com",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "26",
        name: "讯飞星火",
        icon: "sparkles",
        description: "科大讯飞推出的认知大模型，支持文本生成、语言理解、知识问答、逻辑推理、数学解题等功能，已在教育、医疗、办公等多领域落地应用。",
        summary: "科大讯飞认知大模型",
        tags: ["免费", "国产", "大厂"],
        url: "https://xinghuo.xfyun.cn",
        category: "chat",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "27",
        name: "海螺AI",
        icon: "sparkles",
        description: "字节跳动旗下AI对话助手，支持智能问答、内容创作、知识搜索等功能，深度集成抖音和头条内容生态，回答生动有趣，特别适合年轻用户。",
        summary: "字节AI对话助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://hailuoai.com",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "28",
        name: "Coze扣子",
        icon: "sparkles",
        description: "字节跳动推出的AI Bot创建平台，无需编程即可通过可视化方式创建和部署AI聊天机器人，支持插件、工作流和知识库，高效构建智能体应用。",
        summary: "AI Bot创建与部署平台",
        tags: ["免费", "国产", "大厂"],
        url: "https://coze.cn",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "29",
        name: "元宝",
        icon: "sparkles",
        description: "腾讯混元大模型在微信生态的AI助手产品，支持智能对话、公众号内容分析、图片理解等，与微信深度整合，是微信用户便捷使用AI的入口。",
        summary: "腾讯混元微信AI助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://yuanbao.tencent.com",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "30",
        name: "NotebookLM",
        icon: "sparkles",
        description: "Google推出的AI笔记和研究助手，可以上传文档自动生成摘要、问答和播客，支持多文档关联分析，特别适合学术研究、书籍阅读和深度调研。",
        summary: "Google AI研究笔记助手",
        tags: ["免费", "国际", "大厂"],
        url: "https://notebooklm.google.com",
        category: "productivity",
        pricing: "免费",
        featured: false
    },    {
        id: "31",
        name: "Canva AI",
        icon: "sparkles",
        description: "Canva内置的AI设计工具，支持AI生成PPT、海报、社交媒体图片，支持文字生成图像、智能抠图、文案生成等功能，让设计零门槛。",
        summary: "AI智能设计平台",
        tags: ["免费", "国际"],
        url: "https://www.canva.com",
        category: "image",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "32",
        name: "ElevenLabs",
        icon: "sparkles",
        description: "全球领先的AI语音合成和克隆平台，支持30种语言和多种音色，可生成逼真的AI语音、克隆声音、进行多语言配音，适合有声书和视频配音。",
        summary: "AI语音合成与克隆平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://elevenlabs.io",
        category: "audio",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "33",
        name: "HeyGen",
        icon: "sparkles",
        description: "AI驱动的数字人视频生成平台，只需上传照片即可生成逼真的AI数字人视频，支持多语言配音、背景更换和模板化视频制作，适合营销和培训场景。",
        summary: "AI数字人视频生成平台",
        tags: ["付费订阅", "国际"],
        url: "https://heygen.com",
        category: "video",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "34",
        name: "Pika",
        icon: "sparkles",
        description: "新兴的AI视频生成工具，支持文字和图片生成视频，操作简单、生成速度快，社区氛围活跃，特别适合短视频创作者快速生成创意内容。",
        summary: "AI短视频生成工具",
        tags: ["免费", "国际", "创新"],
        url: "https://pika.art",
        category: "video",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "35",
        name: "秘塔AI搜索",
        icon: "sparkles",
        description: "秘塔科技推出的AI搜索引擎，无广告、直达答案，直接给出带来源引用的信息摘要，搜索体验干净高效，特别适合深度信息检索。",
        summary: "无广告AI搜索引擎",
        tags: ["免费", "国产"],
        url: "https://metaso.cn",
        category: "search",
        pricing: "免费",
        featured: true
    },    {
        id: "36",
        name: "夸克AI搜索",
        icon: "sparkles",
        description: "阿里夸克浏览器的AI搜索功能，支持智能问答、摘要生成和多模态搜索，覆盖亿级用户，是国内头部AI搜索产品，响应速度快、准确率高。",
        summary: "夸克浏览器AI搜索",
        tags: ["免费", "国产", "大厂"],
        url: "https://www.quark.cn",
        category: "search",
        pricing: "免费",
        featured: false
    },    {
        id: "37",
        name: "Phind",
        icon: "sparkles",
        description: "专为开发者设计的AI搜索引擎，可以回答编程问题、提供代码示例和解决方案，支持多语言和最新技术栈文档搜索，是程序员的搜索利器。",
        summary: "开发者专属AI搜索引擎",
        tags: ["免费", "国际"],
        url: "https://www.phind.com",
        category: "search",
        pricing: "免费",
        featured: false
    },    {
        id: "38",
        name: "CodeWhisperer",
        icon: "sparkles",
        description: "亚马逊AWS推出的AI代码助手，深度集成于VS Code、IntelliJ等IDE，支持代码补全、代码生成和安全扫描，对AWS开发者特别友好。",
        summary: "亚马逊AI代码助手",
        tags: ["免费", "国际", "大厂"],
        url: "https://aws.amazon.com/codewhisperer",
        category: "code",
        pricing: "免费",
        featured: false
    },    {
        id: "39",
        name: "通义听悟",
        icon: "sparkles",
        description: "阿里云推出的AI会议记录和转写工具，支持实时语音转文字、多语言翻译、会议摘要和关键词提取，大幅提升会议效率和知识管理。",
        summary: "AI会议转写与摘要工具",
        tags: ["免费", "国产", "大厂"],
        url: "https://tingwu.aliyun.com",
        category: "audio",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "40",
        name: "PixVerse",
        icon: "sparkles",
        description: "国产AI视频生成平台，支持文字和图片生成视频，提供多种风格模板，生成速度快、操作简单，适合创作者快速生成高质量短视频内容。",
        summary: "国产AI视频生成工具",
        tags: ["免费", "国产"],
        url: "https://pixverse.ai",
        category: "video",
        pricing: "免费",
        featured: false
    },    {
        id: "41",
        name: "笔灵AI写作",
        icon: "sparkles",
        description: "国内专业AI写作工具，提供100+写作模板，覆盖小红书文案、抖音脚本、工作总结、论文写作等场景，帮助用户快速生成高质量文本内容。",
        summary: "多场景AI写作工具",
        tags: ["免费", "国产"],
        url: "https://ibiling.cn",
        category: "writing",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "42",
        name: "印象AI",
        icon: "sparkles",
        description: "印象笔记推出的AI助手，深度集成于笔记编辑器，支持智能写作、摘要、翻译、续写等功能，结合笔记知识库实现个性化的AI辅助体验。",
        summary: "印象笔记AI写作助手",
        tags: ["免费", "国产"],
        url: "https://yinxiang.com",
        category: "writing",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "43",
        name: "Otter.ai",
        icon: "sparkles",
        description: "AI会议记录和实时转录工具，可以自动识别说话人、生成实时字幕、提炼关键信息并导出会议摘要，是远程会议和采访的高效记录工具。",
        summary: "AI会议转录与摘要工具",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://otter.ai",
        category: "audio",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "44",
        name: "Gemini",
        icon: "sparkles",
        description: "Google推出的多模态AI助手，支持文本、图像、音频、视频的理解和生成，深度集成Google搜索和服务，在多模态任务上表现领先。",
        summary: "Google多模态AI助手",
        tags: ["免费", "国际", "大厂"],
        url: "https://gemini.google.com",
        category: "chat",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "45",
        name: "ComfyUI",
        icon: "sparkles",
        description: "基于节点式工作流的Stable Diffusion用户界面，支持高度自定义的图像生成流程，是AI图像生成领域最强大的开源工具，适合专业创作者和研究人员。",
        summary: "开源节点式AI绘图工作流",
        tags: ["免费", "开源", "国际"],
        url: "https://github.com/comfyanonymous/ComfyUI",
        category: "image",
        pricing: "免费",
        featured: false
    },    {
        id: "46",
        name: "Raycast",
        icon: "sparkles",
        description: "Mac上备受推崇的效率工具，支持AI驱动的快速搜索、剪贴板历史、应用启动、工作流自动化，将Mac生产力提升到全新高度。",
        summary: "Mac AI效率启动器",
        tags: ["免费", "国际", "创新"],
        url: "https://raycast.com",
        category: "productivity",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "47",
        name: "Kimi+",
        icon: "sparkles",
        description: "Kimi的官方智能体扩展市场，提供办公助手、翻译官、代码助手、画图师等多种垂直场景智能体，在Kimi对话中一键切换使用。",
        summary: "Kimi智能体扩展市场",
        tags: ["免费", "国产"],
        url: "https://kimi.moonshot.cn",
        category: "chat",
        pricing: "免费",
        featured: false
    },    {
        id: "48",
        name: "腾讯文档AI",
        icon: "sparkles",
        description: "腾讯文档内置的AI助手，支持智能写作、表格公式生成、内容润色和翻译，深度集成文档、表格和幻灯片，让在线协作更高效。",
        summary: "腾讯文档内置AI助手",
        tags: ["免费", "国产", "大厂"],
        url: "https://docs.qq.com",
        category: "productivity",
        pricing: "免费",
        featured: false
    },    {
        id: "49",
        name: "稿定AI",
        icon: "sparkles",
        description: "稿定设计推出的AI设计工具，支持AI生成海报、电商主图、头像、Logo等设计物料，提供海量模板一键生成，大幅降低设计门槛，适合运营和营销人员。",
        summary: "AI商业设计物料生成工具",
        tags: ["免费", "国产"],
        url: "https://www.gaoding.com",
        category: "image",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "50",
        name: "Dify",
        icon: "sparkles",
        description: "开源的LLM应用开发平台，提供可视化编排、知识库管理、API部署等能力，支持快速构建AI工作流和Agent，适合企业和开发者自建AI应用。",
        summary: "开源LLM应用开发平台",
        tags: ["免费", "开源", "国际"],
        url: "https://dify.ai",
        category: "agent",
        pricing: "免费",
        featured: true
    },    {
        id: "51",
        name: "Coze",
        icon: "sparkles",
        description: "字节跳动面向全球市场的AI Bot平台，支持多模态Agent构建、插件生态和工作流编排，可在Discord、Telegram等平台快速部署智能助手。",
        summary: "字节AI Bot国际化平台",
        tags: ["免费", "国产", "大厂"],
        url: "https://coze.com",
        category: "agent",
        pricing: "免费",
        featured: false
    },    {
        id: "52",
        name: "AutoGen Studio",
        icon: "sparkles",
        description: "微软开源的多Agent协作应用开发框架，支持构建多个AI Agent之间的协作流程，可自定义Agent角色和交互协议，适合构建复杂AI工作流。",
        summary: "微软开源多Agent框架",
        tags: ["免费", "开源", "大厂"],
        url: "https://microsoft.github.io/autogen",
        category: "agent",
        pricing: "免费",
        featured: false
    },    {
        id: "53",
        name: "扣子专业版",
        icon: "sparkles",
        description: "Coze的专业企业版，提供私有化部署、高并发API调用、团队协作和权限管理，适合企业级AI Agent应用的生产环境部署和管理。",
        summary: "Coze企业级AI Agent平台",
        tags: ["付费订阅", "国产", "大厂"],
        url: "https://coze.cn",
        category: "agent",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "54",
        name: "文小言",
        icon: "sparkles",
        description: "百度推出的AI数字人Agent平台，支持快速创建具有特定技能的AI Agent，支持知识库配置、多轮对话和API接入，可嵌入各类业务场景。",
        summary: "百度AI Agent创作平台",
        tags: ["免费", "国产", "大厂"],
        url: "https://xiaoyan.baidu.com",
        category: "agent",
        pricing: "免费",
        featured: false
    },    {
        id: "55",
        name: "Promptport",
        icon: "sparkles",
        description: "专业的AI提示词分享与交易平台，汇集全球优质提示词模板，涵盖写作、编程、设计等场景，支持提示词优化和在线测试，帮助用户快速提升AI使用效果。",
        summary: "AI提示词分享与优化平台",
        tags: ["免费", "国际"],
        url: "https://promptport.ai",
        category: "prompt",
        pricing: "免费",
        featured: false
    },    {
        id: "56",
        name: "Snack Prompt",
        icon: "sparkles",
        description: "社区驱动的AI提示词发现平台，用户可以上传、投票和收藏优质提示词，平台提供提示词分类、难度评级和使用场景标注，是发现优质提示词的好去处。",
        summary: "社区AI提示词发现平台",
        tags: ["免费", "国际"],
        url: "https://snackprompt.com",
        category: "prompt",
        pricing: "免费",
        featured: false
    },    {
        id: "57",
        name: "PromptPerfect",
        icon: "sparkles",
        description: "AI提示词自动优化工具，支持对ChatGPT、Claude、Midjourney等模型的提示词进行结构化优化，自动补全细节和约束条件，显著提升AI输出质量。",
        summary: "AI提示词自动优化工具",
        tags: ["免费", "国际"],
        url: "https://promptperfect.jina.ai",
        category: "prompt",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "58",
        name: " AIPRM",
        icon: "sparkles",
        description: "Chrome浏览器扩展，为ChatGPT提供精选提示词库和浏览器自动化功能，支持一键调用各类场景提示词，是ChatGPT用户提升效率的必备工具。",
        summary: "ChatGPT提示词浏览器扩展",
        tags: ["免费", "国际"],
        url: "https://aiprm.com",
        category: "prompt",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "59",
        name: "FlowGPT",
        icon: "sparkles",
        description: "全球最大的ChatGPT提示词社区之一，汇集超过十万条精选提示词，支持按场景、模型和语言筛选，提供提示词创作工具和积分激励机制。",
        summary: "全球最大ChatGPT提示词社区",
        tags: ["免费", "国际"],
        url: "https://flowgpt.com",
        category: "prompt",
        pricing: "免费",
        featured: false
    },    {
        id: "60",
        name: "LangChain",
        icon: "sparkles",
        description: "全球最流行的LLM应用开发框架，提供Prompt模板、Chain组合、Agent构建、记忆管理和向量检索等模块，是构建复杂AI应用的基础架构首选。",
        summary: "全球最流行LLM应用开发框架",
        tags: ["免费", "开源", "国际"],
        url: "https://www.langchain.com",
        category: "dev",
        pricing: "免费",
        featured: true
    },    {
        id: "61",
        name: "Fireworks AI",
        icon: "sparkles",
        description: "高性能AI模型推理平台，提供业界领先的推理速度和吞吐量，支持开源大模型的API调用，价格比OpenAI低数十倍，适合大规模AI应用部署。",
        summary: "高性能AI推理加速平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://fireworks.ai",
        category: "dev",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "62",
        name: "Replicate",
        icon: "sparkles",
        description: "云端AI模型运行平台，汇集数千个开源AI模型，支持通过API调用图像生成、视频生成、语音合成等模型，无需本地部署，按调用量计费。",
        summary: "开源AI模型云端运行平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://replicate.com",
        category: "dev",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "63",
        name: "Groq",
        icon: "sparkles",
        description: "搭载自研LPU芯片的AI推理引擎，提供业界最快的大模型推理速度，支持开源模型的API调用，延迟极低，特别适合对实时性要求高的AI应用。",
        summary: "极速AI推理引擎",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://groq.com",
        category: "dev",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "64",
        name: "Together AI",
        icon: "sparkles",
        description: "开源AI模型聚合推理平台，提供Llama、Mistral、DeepSeek等主流开源模型的API，支持模型微调和RLHF训练，是开源模型调用的高性价比选择。",
        summary: "开源大模型聚合推理平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://together.ai",
        category: "dev",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "65",
        name: "Julius AI",
        icon: "sparkles",
        description: "AI驱动的数据分析助手，用户可以用自然语言描述数据分析需求，Julius自动完成数据清洗、统计分析和可视化生成，支持Excel、CSV等常见格式。",
        summary: "自然语言数据分析助手",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://julius.ai",
        category: "data",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "66",
        name: "SQL Chat",
        icon: "sparkles",
        description: "基于ChatGPT的SQL查询助手，用户用自然语言描述数据查询需求，系统自动生成SQL语句，支持连接数据库进行查询和可视化，适合数据分析师和运营人员。",
        summary: "自然语言转SQL查询助手",
        tags: ["免费", "国际"],
        url: "https://sqlchat.ai",
        category: "data",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "67",
        name: "MonkeyLearn",
        icon: "sparkles",
        description: "无需编程的机器学习数据分析平台，提供文本分类、情感分析和关键词提取等AI模型，支持拖拽式工作流构建，适合非技术人员进行数据洞察。",
        summary: "无代码机器学习数据分析平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://monkeylearn.com",
        category: "data",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "68",
        name: "Tableau AI",
        icon: "sparkles",
        description: "Salesforce旗下Tableau推出的AI数据分析功能，支持自然语言查询数据、自动化洞察发现和智能可视化推荐，让数据分析更加直观和高效。",
        summary: "AI增强的商业智能分析",
        tags: ["付费订阅", "国际", "大厂"],
        url: "https://www.tableau.com",
        category: "data",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "69",
        name: "Kimi Data",
        icon: "sparkles",
        description: "Kimi推出的AI数据分析功能，支持上传CSV、Excel等数据文件，用自然语言进行数据查询和分析，自动生成可视化图表，适合日常办公数据分析场景。",
        summary: "Kimi数据分析智能助手",
        tags: ["免费", "国产"],
        url: "https://kimi.moonshot.cn",
        category: "data",
        pricing: "免费",
        featured: false
    },    {
        id: "70",
        name: "Tripo3D",
        icon: "sparkles",
        description: "AI驱动的3D模型生成工具，只需上传一张图片即可在数秒内生成高质量3D模型，支持导出为OBJ、GLTF等通用格式，广泛用于游戏、VR和工业设计领域。",
        summary: "AI图片转3D模型生成工具",
        tags: ["免费", "国际", "创新"],
        url: "https://trip3d.ai",
        category: "3d",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "71",
        name: "Meshy",
        icon: "sparkles",
        description: "AI 3D建模平台，支持文字生成3D模型、图片生成3D模型和3D纹理贴图，生成的模型可直接用于游戏和元宇宙项目，大幅降低3D内容创作门槛。",
        summary: "AI文字图片转3D建模平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://meshy.ai",
        category: "3d",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "72",
        name: "Kaedim",
        icon: "sparkles",
        description: "AI游戏3D资产生成平台，通过文字描述生成游戏级别的3D角色和道具模型，生成结果可直接导入Unity、Unreal等主流游戏引擎使用。",
        summary: "AI游戏3D资产生成平台",
        tags: ["付费订阅", "国际"],
        url: "https://www.kaedim3d.com",
        category: "3d",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "73",
        name: "Sloyd",
        icon: "sparkles",
        description: "参数化AI 3D建模工具，用户描述想要的3D对象类型和风格，系统自动生成包含完整拓扑结构的3D模型，支持游戏资产和建筑可视化快速原型制作。",
        summary: "AI参数化3D建模工具",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://www.sloyd.ai",
        category: "3d",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "74",
        name: "AutoGPT",
        icon: "sparkles",
        description: "自主AI Agent开源项目，能够将复杂目标拆解为多个子任务并自动执行，支持连接外部工具和API，被视为AGI发展的重要里程碑。",
        summary: "自主执行任务的AI Agent",
        tags: ["免费", "开源", "国际"],
        url: "https://news.agpt.co",
        category: "agent",
        pricing: "免费",
        featured: true
    },    {
        id: "75",
        name: "Rabbit R1",
        icon: "sparkles",
        description: "AI端侧硬件设备，通过大动作模型（LAM）实现对手机App的操控，无需API接口即可操作任意应用，代表了AI硬件的创新方向。",
        summary: "AI端侧操作智能硬件",
        tags: ["付费订阅", "国际", "创新"],
        url: "https://www.rabbit.tech",
        category: "hardware",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "76",
        name: "Pipecat",
        icon: "sparkles",
        description: "开源AI语音对话框架，支持构建多模态AI助手、语音播客和实时对话Agent，可接入多种LLM和TTS引擎，适合开发AI语音硬件和实时对话应用。",
        summary: "开源AI语音对话开发框架",
        tags: ["免费", "开源", "国际"],
        url: "https://pipecat.ai",
        category: "hardware",
        pricing: "免费",
        featured: false
    },    {
        id: "77",
        name: "Mycroft AI",
        icon: "sparkles",
        description: "全球首个开源隐私优先的AI语音助手，支持本地部署无需联网，支持音乐播放、智能家居控制、新闻播报等技能，可运行在树莓派等硬件上。",
        summary: "开源本地AI语音助手",
        tags: ["免费", "开源", "国际"],
        url: "https://mycroft.ai",
        category: "hardware",
        pricing: "免费",
        featured: false
    },    {
        id: "78",
        name: "Credo AI",
        icon: "sparkles",
        description: "企业级AI治理与合规平台，提供AI风险评估、模型审计、公平性监测和合规报告功能，帮助企业在AI部署全生命周期内满足监管要求。",
        summary: "企业AI治理与合规平台",
        tags: ["付费订阅", "国际"],
        url: "https://www.credo.ai",
        category: "security",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "79",
        name: "Fiddler AI",
        icon: "sparkles",
        description: "AI模型可解释性和监控平台，帮助企业分析AI模型的决策过程，检测模型偏差和漂移，支持生产环境的模型性能监控和合规审计。",
        summary: "AI模型可解释性监控平台",
        tags: ["付费订阅", "国际"],
        url: "https://www.fiddler.ai",
        category: "security",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "80",
        name: "Protect AI",
        icon: "sparkles",
        description: "AI安全扫描和模型保护平台，提供神经网络后门检测、投毒攻击防御和模型水印等安全功能，帮助开发者识别和消除AI模型中的安全威胁。",
        summary: "AI模型安全扫描平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://protectai.com",
        category: "security",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "81",
        name: "Holistic AI",
        icon: "sparkles",
        description: "AI伦理和公平性评估平台，提供模型偏见检测、歧视性结果识别和合规性评估报告，已被多家财富500强企业用于AI系统的伦理审查。",
        summary: "AI伦理公平性评估平台",
        tags: ["付费订阅", "国际"],
        url: "https://www.holisticai.com",
        category: "security",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "82",
        name: "Khan Academy Khanmigo",
        icon: "sparkles",
        description: "可汗学院推出的AI导师Khanmigo，基于苏格拉底式引导教学法，为学生提供个性化学习指导、作业批改和学习规划，覆盖数学、编程、科学等学科。",
        summary: "可汗学院AI导师",
        tags: ["免费", "国际", "大厂"],
        url: "https://www.khanacademy.org",
        category: "education",
        pricing: "免费",
        featured: true
    },    {
        id: "83",
        name: "Duolingo Max",
        icon: "sparkles",
        description: "Duolingo基于大语言模型推出的AI语言学习订阅服务，提供AI角色扮演对话和精准语法解释，实现与AI进行真实场景口语练习的沉浸式语言学习体验。",
        summary: "AI口语陪练语言学习",
        tags: ["付费订阅", "国际"],
        url: "https://www.duolingo.com",
        category: "education",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "84",
        name: "SecurifAI",
        icon: "sparkles",
        description: "面向青少年的AI安全教育平台，通过互动课程和场景模拟帮助青少年理解AI的潜在风险、隐私保护和信息辨别，培养负责任的AI使用习惯。",
        summary: "AI安全素养教育平台",
        tags: ["免费", "国产"],
        url: "https://securifai.com",
        category: "education",
        pricing: "免费",
        featured: false
    },    {
        id: "85",
        name: "Coursera AI",
        icon: "sparkles",
        description: "Coursera平台推出的AI辅助学习功能，提供AI编程答疑、作业辅导和个性化学习路径规划，支持与AI导师进行多轮对话深入理解知识点。",
        summary: "Coursera AI学习辅助",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://www.coursera.org",
        category: "education",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "86",
        name: "讯飞智学",
        icon: "sparkles",
        description: "科大讯飞面向K12教育的AI学习平台，基于星火大模型提供个性化学习推荐、作文批改和口语评测，已覆盖全国数万所学校和数百万学生用户。",
        summary: "讯飞AI个性化学习平台",
        tags: ["免费", "国产", "大厂"],
        url: "https://zhixue.com",
        category: "education",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "87",
        name: "MasterGo AI",
        icon: "sparkles",
        description: "协同时式UI设计工具MasterGo推出的AI功能，支持AI生成UI界面、智能布局、图标生成和设计规范检查，大幅提升设计师和产研团队的协作效率。",
        summary: "协同时式UI设计AI工具",
        tags: ["免费", "国产"],
        url: "https://mastergo.com",
        category: "design",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "88",
        name: "Figma AI",
        icon: "sparkles",
        description: "全球最流行的UI设计工具Figma推出的AI功能套件，包括AI生成设计稿、自动命名图层、搜索设计元素和生成性填充，是设计师的高效助手。",
        summary: "Figma设计AI助手",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://figma.com",
        category: "design",
        pricing: "付费订阅",
        featured: false
    },    {
        id: "89",
        name: "Phidata",
        icon: "sparkles",
        description: "构建具有记忆和知识库的AI助手的开发框架，支持为AI Agent添加向量数据库检索、工具调用和工作流编排，快速构建具备领域知识的AI应用。",
        summary: "知识增强AI助手开发框架",
        tags: ["免费", "开源", "国际"],
        url: "https://phidata.app",
        category: "search",
        pricing: "免费",
        featured: false
    },    {
        id: "90",
        name: "沉浸式翻译",
        icon: "sparkles",
        description: "免费的AI双语网页翻译浏览器扩展，支持在任意网页上显示中英对照翻译，集成多种AI翻译引擎，告别机翻味，是阅读外文资料的利器。",
        summary: "AI双语对照网页翻译扩展",
        tags: ["免费", "国产"],
        url: "https://immersivetranslate.com",
        category: "writing",
        pricing: "免费",
        featured: true
    },    {
        id: "91",
        name: "Tabnine",
        icon: "sparkles",
        description: "AI代码补全工具，支持所有主流编程语言和IDE，基于开源代码训练的私有化部署选项，确保代码隐私安全，适合企业和注重代码安全的企业开发团队。",
        summary: "隐私安全的AI代码补全",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://www.tabnine.com",
        category: "code",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "92",
        name: "通义效率",
        icon: "sparkles",
        description: "阿里云通义系列中的效率工具集合，包含AI会议摘要、文档总结、脑暴助手和日程规划等功能，是职场人士提升工作效率的一站式AI工具箱。",
        summary: "阿里职场AI效率工具箱",
        tags: ["免费", "国产", "大厂"],
        url: "https://tongyi.aliyun.com",
        category: "productivity",
        pricing: "免费",
        featured: false
    },    {
        id: "93",
        name: "剪映",
        icon: "sparkles",
        description: "字节跳动旗下国民级视频剪辑工具，内置强大的AI功能，包括AI配音、AI字幕、AI消除和AI克隆音色，让视频创作门槛大幅降低。",
        summary: "字节AI智能视频剪辑工具",
        tags: ["免费", "国产", "大厂"],
        url: "https://www.capcut.cn",
        category: "video",
        pricing: "免费",
        featured: true
    },    {
        id: "94",
        name: "Zapier Central",
        icon: "sparkles",
        description: "Zapier推出的AI Agent平台，允许用户用自然语言构建跨数千款SaaS工具的自动化工作流，无需编程即可实现复杂业务自动化。",
        summary: "AI驱动的SaaS自动化平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://zapier.com",
        category: "agent",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "95",
        name: "Upscayl",
        icon: "sparkles",
        description: "免费开源的本地AI图片放大工具，基于开源模型，支持将低分辨率图片无损放大4-16倍，生成清晰的超分辨率图像，适合老照片修复和素材放大。",
        summary: "开源本地AI图片放大工具",
        tags: ["免费", "开源", "国际"],
        url: "https://upscayl.org",
        category: "image",
        pricing: "免费",
        featured: false
    },    {
        id: "96",
        name: "剪映专业版语音",
        icon: "sparkles",
        description: "剪映专业版内置的AI语音合成和克隆功能，支持数十种音色和方言选择，可克隆个人声音自动配音，大幅降低视频配音成本。",
        summary: "AI语音合成克隆工具",
        tags: ["免费", "国产", "大厂"],
        url: "https://www.capcut.cn",
        category: "audio",
        pricing: "免费",
        featured: false
    },    {
        id: "97",
        name: "Scenario",
        icon: "sparkles",
        description: "AI游戏资产生成平台，支持为游戏开发者批量生成风格一致的场景、角色和道具贴图，支持Unity和Unreal引擎插件，大幅加速游戏美术制作流程。",
        summary: "AI游戏美术资产生成平台",
        tags: ["免费", "付费订阅", "国际"],
        url: "https://www.scenario.com",
        category: "design",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "98",
        name: "扣子生活",
        icon: "sparkles",
        description: "扣子平台的AI生活助手集合，提供健康饮食规划、旅行行程制定、健身指导和法律咨询等多种垂直场景Bot，一站式解决日常生活需求。",
        summary: "扣子AI生活助手集合",
        tags: ["免费", "国产"],
        url: "https://coze.cn",
        category: "productivity",
        pricing: "免费",
        featured: false
    },    {
        id: "99",
        name: "DeepSeek",
        icon: "sparkles",
        description: "深度求索推出的国产开源大模型和AI助手，推理能力强、性价比极高，支持代码、数学、写作等多任务，开源模型DeepSeek-Coder和DeepSeek-Math在多项评测中领先。",
        summary: "深度求索国产开源大模型",
        tags: ["免费", "开源", "国产"],
        url: "https://www.deepseek.com",
        category: "chat",
        pricing: "免费",
        featured: true
    },    {
        id: "100",
        name: "Notion",
        icon: "sparkles",
        description: "全能笔记与项目管理工具，支持协作文档、数据库、任务看板。AI助手可自动总结会议纪要、生成任务清单，是项目经理和团队的效率神器。",
        summary: "全能笔记+项目管理，团队效率工具",
        tags: ["免费", "付费"],
        url: "https://www.notion.so",
        category: "pm",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "101",
        name: "飞书",
        icon: "sparkles",
        description: "字节跳动出品的一站式办公平台，集成即时通讯、视频会议、在线文档、项目管理。支持AI助手「豆包」嵌入，提供智能会议纪要、任务拆解等功能。",
        summary: "一站式企业办公+项目管理平台",
        tags: ["免费", "国产"],
        url: "https://www.feishu.cn",
        category: "pm",
        pricing: "免费",
        featured: true
    },    {
        id: "102",
        name: "Linear",
        icon: "sparkles",
        description: "专为开发者设计的敏捷项目管理工具，界面简洁优雅。与GitHub深度集成，支持Issue跟踪、Sprint规划、路线图管理。AI功能可自动生成Issue描述和代码审查建议。",
        summary: "开发者友好的敏捷项目管理工具",
        tags: ["免费", "付费", "开源"],
        url: "https://linear.app",
        category: "pm",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "103",
        name: "Miro",
        icon: "sparkles",
        description: "在线白板与协作工具，支持头脑风暴、流程图、用户故事地图等。AI功能可自动将白板内容整理为结构化文档，生成会议摘要，是远程团队协作的首选。",
        summary: "在线白板+团队协作可视化工具",
        tags: ["免费", "付费"],
        url: "https://miro.com",
        category: "pm",
        pricing: "免费+付费",
        featured: true
    },    {
        id: "104",
        name: "GitHub Projects",
        icon: "sparkles",
        description: "GitHub官方的项目管理工作区，支持看板和表格两种视图。与代码仓库、PR、Issue深度绑定。AI辅助可自动分类Issue、预测工时、生成项目报告。",
        summary: "GitHub官方项目跟踪与敏捷看板",
        tags: ["免费", "开源"],
        url: "https://github.com/features/issues",
        category: "pm",
        pricing: "免费",
        featured: true
    },    {
        id: "105",
        name: "Trello",
        icon: "sparkles",
        description: "简洁直观的看板式项目管理工具，基于卡片和列表管理任务。支持Power-Up插件扩展，AI插件可自动整理卡片、生成摘要，适合中小团队快速上手。",
        summary: "看板式轻量级项目管理工具",
        tags: ["免费", "付费"],
        url: "https://trello.com",
        category: "pm",
        pricing: "免费+付费",
        featured: false
    },    {
        id: "106",
        name: "钉钉",
        icon: "sparkles",
        description: "阿里巴巴出品的企业通讯与项目管理平台。集成IM、视频会议、OA审批、项目管理等多功能。AI助理「通义」可处理会议转写、任务分配、数据报表等。",
        summary: "企业级协同办公与AI项目管理",
        tags: ["免费", "国产"],
        url: "https://www.dingtalk.com",
        category: "pm",
        pricing: "免费",
        featured: false
    }
];
